const messages = {
  en: {
    "settings.categories": "Settings categories", "settings.category.general": "General", "settings.category.privacy": "Privacy", "settings.category.appearance": "Display", "settings.category.update": "Updates",
    "help.guide": "Mote Tips", "help.guideSubtitle": "Learn every feature", "help.topicStart": "Getting started", "help.topicContent": "Rich content", "help.topicMultiple": "Multiple paste", "help.topicManage": "Organize & recover", "help.topicPermissions": "Permissions", "help.startTitle": "Copy, find, and paste.", "help.startIntro": "Mote stays out of the way until you need something you copied.", "help.exampleText": "A useful paragraph", "help.exampleSaved": "Saved automatically", "help.exampleSearch": "Search copied content…", "help.contentEyebrow": "SMART CONTENT", "help.contentTitle": "Mote understands what you copy.", "help.contentIntro": "A record keeps its real content and shows the actions that make sense for it.", "help.combinedTitle": "Keep a combined copy together", "help.combinedBody": "Text, images, and files copied at the same moment remain one ordered record.", "help.exampleCombined": "Image + caption", "help.exampleOneRecord": "One clipboard record", "help.colorsTitle": "Pick colors from an image", "help.colorsBody": "Mote extracts a small palette. Select a swatch to copy its HEX value.", "help.actionsTitle": "Use the right action", "help.actionsBody": "Open links in the browser, reveal files in their folder, and copy colors as HEX or RGB.", "help.multiIntro": "Collect several records first, then paste them as one ordered sequence.", "help.multiSelectTitle": "Build a paste list", "help.queue1": "First answer", "help.queue2": "Second answer", "help.queue3": "Final link", "help.orderTitle": "Earliest copy goes first", "help.orderBody": "Numbered items are pasted from 1 onward, matching the order you collected them.", "help.manageEyebrow": "KEEP CONTROL", "help.manageTitle": "Keep important things safe.", "help.manageIntro": "Pin records you reuse, recover accidental deletion, and see when a file has moved.", "help.pinTitle": "Pin what you reuse", "help.pinBody": "Pinned records stay at the top and are not removed when you clear history.", "help.undoTitle": "Undo a deletion", "help.undoBody": "After deleting one record or clearing history, use Undo within seven seconds to restore it.", "help.missingTitle": "Know when a file moved", "help.missingBody": "Mote marks file records whose original file is no longer at the saved location.", "help.permissionTitle": "See exactly what Mote needs.", "help.permissionIntro": "Permission status stays visible in Settings, with a direct path to fix anything missing.", "help.captureBody": "Clipboard recording saves new copies locally while it is enabled.",
    "shortcut.title": "Keyboard shortcuts", "shortcut.intro": "Select a shortcut, then press the key combination you want to use.", "shortcut.hint": "Each action needs a different shortcut. Escape cancels recording.", "shortcut.close": "Close keyboard shortcuts", "shortcut.settingsDetail": "Open a separate panel to view and customize shortcuts",
    "action.openLink": "Open link", "action.showInFinder": "Show in folder", "action.copyHex": "Copy HEX", "action.copyRgb": "Copy RGB", "action.copyColor": "Copy {color}",
    "settings.permissions": "PERMISSIONS & STATUS", "permission.capture": "Clipboard recording", "permission.autoPaste": "Automatic paste", "permission.ready": "Ready", "permission.captureOff": "Turn on Capture clipboard above", "permission.accessibilityNeeded": "Permission is needed to paste into other apps", "permission.fix": "Open Settings", "permission.checkAgain": "Check again", "permission.helpTitle": "Allow automatic paste", "permission.helpBody": "Mote needs Accessibility permission only to send the paste shortcut to the app you were using.", "permission.windowsPasteBody": "Mote sends Ctrl+V to the window you were using; no separate accessibility permission is required.",
    "undo.deletedOne": "Record deleted", "undo.deletedMany": "{count} records deleted", "undo.action": "Undo", "detail.fileMissing": "Original file is unavailable", "detail.extractedColors": "Colors from this image",
    "app.clipboard": "Clipboard", "app.pinSelected": "Pin selected item", "app.openHelp": "Open help", "app.openSettings": "Open settings",
    "search.placeholder": "Search everything you copied…", "search.label": "Search clipboard history", "search.clear": "Clear search", "search.paste": "Paste", "search.open": "Open",
    "action.copy": "Copy", "action.copied": "Copied", "action.paste": "Paste", "action.pasted": "Pasted", "action.pastedCount": "Pasted {count}", "action.pin": "Pin", "action.pinned": "Pinned", "action.delete": "Delete", "action.cancel": "Cancel", "action.selectAll": "Select all",
    "empty.clipboard": "Your clipboard is clear", "confirm.clearTitle": "Clear clipboard history?", "confirm.clearDetail": "All unpinned records will be permanently removed. Pinned records will stay in Mote.", "confirm.clearAction": "Clear history", "confirm.clearing": "Clearing…", "confirm.cancel": "Cancel",
    "history.label": "Clipboard history", "history.loading": "Loading history…", "history.unavailable": "History unavailable", "history.selectedCount": "{count} selected", "history.select": "Select", "history.today": "Today", "history.earlier": "Earlier", "history.yesterday": "Yesterday", "history.noMatches": "No matches", "history.tryDifferent": "Try a different word or phrase.",
    "multi.label": "MULTIPLE PASTE", "multi.emptyTitle": "Select a few items", "multi.countTitle": "{count} item selected", "multi.countTitlePlural": "{count} items selected", "multi.explainer": "Items will be pasted from the earliest copy to the latest.", "multi.move": "Move", "multi.addRemove": "Select / remove", "multi.paste": "Paste selected", "multi.pasteCount": "Paste {count}",
    "settings.title": "Settings", "settings.subtitle": "Mote preferences", "settings.general": "GENERAL", "settings.language": "Language", "settings.languageDetail": "Choose the language used in Mote", "settings.auto": "Follow system", "settings.english": "English", "settings.chinese": "简体中文", "settings.capture": "Capture clipboard", "settings.captureDetail": "Save new copies automatically", "settings.directPaste": "Paste on Enter", "settings.directPasteDetail": "Paste directly into the last app", "settings.launch": "Launch at login", "settings.launchDetail": "Keep Mote ready in the menu bar", "settings.shortcuts": "KEYBOARD SHORTCUTS", "settings.openMote": "Open Mote", "settings.openMoteDetail": "Available from any app", "settings.openMultiple": "Open multiple paste", "settings.openMultipleDetail": "Open directly in multiple selection", "settings.toggleMultiple": "Toggle multiple selection", "settings.toggleMultipleDetail": "Works while Mote is open", "settings.pressKeys": "Press keys…", "settings.privacy": "PRIVACY & STORAGE", "settings.ignorePasswords": "Ignore password managers", "settings.ignorePasswordsDetail": "Skip copies from sensitive apps", "settings.historyLimit": "History limit", "settings.historyLimitDetail": "Maximum saved items", "settings.keepHistory": "Keep history", "settings.keepHistoryDetail": "Automatically remove old items", "settings.days": "{count} days", "settings.forever": "Forever", "settings.accessibility": "ACCESSIBILITY", "settings.reduceMotion": "Reduce motion", "settings.reduceMotionDetail": "Use quieter visual effects", "settings.clear": "Clear unpinned history",
    "help.quickStart": "QUICK START", "help.title": "Your clipboard, close at hand.", "help.intro": "Four simple actions are all you need to use Mote.", "help.copyTitle": "Copy anything", "help.copyBody": "Text, links, images, files, and rich content are saved together.", "help.findTitle": "Find it instantly", "help.findBody": "Open Mote from anywhere, then type to search your history.", "help.pasteTitle": "Paste it back", "help.pasteBody": "Choose an item and send it straight to the app you were using.", "help.multiTitle": "Paste several items", "help.multiBody": "Select several records and Mote pastes them from the earliest copy to the latest. Toggle inside Mote with {shortcut}.", "help.private": "Private by default", "help.privateBody": "Everything stays in a local SQLite database on this device.", "help.done": "Got it", "help.close": "Close help",
    "error.close": "Close error", "error.actionNeeded": "ACTION NEEDED", "error.pasteTitle": "Mote couldn’t paste automatically", "error.genericTitle": "Something went wrong", "error.accessibilityDetail": "Allow Mote under System Settings → Privacy & Security → Accessibility, then try again.", "error.openSettings": "Open System Settings", "error.dismiss": "Close", "error.shortcutDifferent": "Choose a different key combination for each shortcut.", "error.shortcutRegister": "That shortcut is already in use. Try another key combination.", "error.shortcutInvalid": "Mote couldn’t understand that shortcut. Please record it again.",
    "update.section": "SOFTWARE UPDATE", "update.settingsTitle": "Mote updates", "update.version": "Version {version}", "update.check": "Check now", "update.checkingAction": "Checking…", "update.checkedAction": "Up to date", "update.checking": "Contacting GitHub Releases…", "update.current": "Mote is up to date", "update.checkFailed": "Couldn’t reach GitHub Releases", "update.eyebrow": "SOFTWARE UPDATE", "update.title": "Mote {version} is available", "update.detail": "This update is ready to download from GitHub Releases.", "update.install": "Update and restart", "update.later": "Later", "update.downloading": "Downloading {progress}%", "update.progress": "Update download {progress}%", "update.restarting": "The update is installed. Mote is restarting…", "update.restartingShort": "Restarting…", "update.failedEyebrow": "UPDATE PAUSED", "update.failedTitle": "Mote couldn’t update", "update.failedDetail": "Check your connection and try again. Your clipboard history is unchanged.", "update.retry": "Try again",
    "detail.formats": "Available clipboard formats", "detail.compound": "Combined copy · {count} items", "detail.item": "Item {count}", "type.text": "Text", "type.html": "HTML", "type.image": "Image", "type.files": "Files", "type.url": "Link", "type.color": "Color", "type.code": "Code", "type.mixed": "Combined copy", "detail.copied": "Copied {time}", "detail.todayAt": "today at {time}", "detail.color": "Clipboard color", "detail.htmlSource": "HTML source", "unit.characters": "characters", "unit.lines": "lines", "key.enter": "Enter", "key.space": "Space",
  },
  zh: {
    "settings.categories": "设置分类", "settings.category.general": "常规", "settings.category.privacy": "隐私", "settings.category.appearance": "显示", "settings.category.update": "更新",
    "help.guide": "Mote 技巧", "help.guideSubtitle": "了解每一项功能", "help.topicStart": "开始使用", "help.topicContent": "丰富内容", "help.topicMultiple": "多条粘贴", "help.topicManage": "整理与恢复", "help.topicPermissions": "权限说明", "help.startTitle": "复制、查找，然后粘贴。", "help.startIntro": "Mote 平时安静地记录，需要时再帮你找回复制过的内容。", "help.exampleText": "一段有用的文字", "help.exampleSaved": "已经自动保存", "help.exampleSearch": "搜索复制过的内容…", "help.contentEyebrow": "智能内容", "help.contentTitle": "复制什么，就按什么来处理。", "help.contentIntro": "每条记录保留真实内容，并只显示适合这类内容的操作。", "help.combinedTitle": "联合复制保持在一起", "help.combinedBody": "同一次复制中的文字、图片和文件会按原顺序保存在一条记录中。", "help.exampleCombined": "图片 + 说明文字", "help.exampleOneRecord": "同一条剪贴板记录", "help.colorsTitle": "从图片中提取颜色", "help.colorsBody": "Mote 会提取一组主要颜色，点击色块即可复制 HEX 色值。", "help.actionsTitle": "显示合适的操作", "help.actionsBody": "链接可以打开，文件可以在访达中显示，颜色可以复制为 HEX 或 RGB。", "help.multiIntro": "先收集多条记录，再按照确定的顺序一次粘贴。", "help.multiSelectTitle": "建立粘贴列表", "help.queue1": "第一段回答", "help.queue2": "第二段回答", "help.queue3": "最后一个链接", "help.orderTitle": "最早复制的先粘贴", "help.orderBody": "列表会显示 1、2、3 的顺序，并从第 1 条开始依次粘贴。", "help.manageEyebrow": "安心整理", "help.manageTitle": "重要内容不会轻易丢失。", "help.manageIntro": "常用内容可以置顶，误删可以撤销，原文件移动后也会明确提示。", "help.pinTitle": "置顶常用内容", "help.pinBody": "置顶记录会留在列表顶部，清除历史时也不会被删除。", "help.undoTitle": "撤销误删", "help.undoBody": "删除单条记录或清空历史后，可在 7 秒内点击“撤销”恢复。", "help.missingTitle": "发现文件已经移动", "help.missingBody": "如果原文件不在保存时的位置，Mote 会在记录和预览中标记失效。", "help.permissionTitle": "清楚知道 Mote 需要什么。", "help.permissionIntro": "设置中会显示权限状态，缺少权限时可以直接前往修复。", "help.captureBody": "开启后，Mote 会在本机自动保存新的复制内容。",
    "shortcut.title": "键盘快捷键", "shortcut.intro": "点击一项快捷键，然后按下你想使用的新组合。", "shortcut.hint": "每个操作需要使用不同的组合；按 Esc 可以取消录制。", "shortcut.close": "关闭快捷键设置", "shortcut.settingsDetail": "在单独的面板中查看并自定义快捷键",
    "action.openLink": "打开链接", "action.showInFinder": "在文件夹中显示", "action.copyHex": "复制 HEX", "action.copyRgb": "复制 RGB", "action.copyColor": "复制 {color}",
    "settings.permissions": "权限与状态", "permission.capture": "剪贴板记录", "permission.autoPaste": "自动粘贴", "permission.ready": "可以使用", "permission.captureOff": "请先打开上方的“记录剪贴板”", "permission.accessibilityNeeded": "需要权限才能粘贴到其他应用", "permission.fix": "打开系统设置", "permission.checkAgain": "重新检查", "permission.helpTitle": "允许自动粘贴", "permission.helpBody": "Mote 只会使用辅助功能权限，把粘贴快捷键发送到你刚才使用的应用。", "permission.windowsPasteBody": "Mote 会把 Ctrl+V 发送到你刚才使用的窗口，不需要单独授予辅助功能权限。",
    "undo.deletedOne": "已删除 1 条记录", "undo.deletedMany": "已删除 {count} 条记录", "undo.action": "撤销", "detail.fileMissing": "原文件已失效", "detail.extractedColors": "从图片中提取的颜色",
    "app.clipboard": "剪贴板", "app.pinSelected": "置顶当前记录", "app.openHelp": "打开帮助", "app.openSettings": "打开设置",
    "search.placeholder": "搜索复制过的内容…", "search.label": "搜索剪贴板记录", "search.clear": "清除搜索", "search.paste": "粘贴", "search.open": "打开",
    "action.copy": "复制", "action.copied": "已复制", "action.paste": "粘贴", "action.pasted": "已粘贴", "action.pastedCount": "已粘贴 {count} 条", "action.pin": "置顶", "action.pinned": "已置顶", "action.delete": "删除", "action.cancel": "取消", "action.selectAll": "全部选择",
    "empty.clipboard": "剪贴板记录为空", "confirm.clearTitle": "清除剪贴板记录？", "confirm.clearDetail": "所有未置顶的记录都会被永久删除，已经置顶的记录会继续保留。", "confirm.clearAction": "清除记录", "confirm.clearing": "正在清除…", "confirm.cancel": "取消",
    "history.label": "剪贴板记录", "history.loading": "正在加载记录…", "history.unavailable": "暂时无法读取记录", "history.selectedCount": "已选择 {count} 条", "history.select": "多选", "history.today": "今天", "history.earlier": "更早", "history.yesterday": "昨天", "history.noMatches": "没有找到结果", "history.tryDifferent": "换个关键词试试。",
    "multi.label": "多条粘贴", "multi.emptyTitle": "请选择几条记录", "multi.countTitle": "已选择 {count} 条", "multi.countTitlePlural": "已选择 {count} 条", "multi.explainer": "将按照复制时间，从最早的一条开始依次粘贴。", "multi.move": "移动", "multi.addRemove": "选择 / 取消", "multi.paste": "粘贴已选内容", "multi.pasteCount": "粘贴 {count} 条",
    "settings.title": "设置", "settings.subtitle": "Mote 偏好设置", "settings.general": "常规", "settings.language": "语言", "settings.languageDetail": "选择 Mote 使用的界面语言", "settings.auto": "跟随系统", "settings.english": "English", "settings.chinese": "简体中文", "settings.capture": "记录剪贴板", "settings.captureDetail": "自动保存新复制的内容", "settings.directPaste": "回车直接粘贴", "settings.directPasteDetail": "直接粘贴到刚才使用的应用", "settings.launch": "登录时启动", "settings.launchDetail": "让 Mote 随时在菜单栏待命", "settings.shortcuts": "快捷键", "settings.openMote": "打开 Mote", "settings.openMoteDetail": "可在任何应用中使用", "settings.openMultiple": "打开多条粘贴", "settings.openMultipleDetail": "直接进入多选模式", "settings.toggleMultiple": "切换多选模式", "settings.toggleMultipleDetail": "在 Mote 窗口内使用", "settings.pressKeys": "请按快捷键…", "settings.privacy": "隐私与存储", "settings.ignorePasswords": "忽略密码管理器", "settings.ignorePasswordsDetail": "不记录敏感应用中的复制内容", "settings.historyLimit": "记录上限", "settings.historyLimitDetail": "最多保存多少条记录", "settings.keepHistory": "保留时间", "settings.keepHistoryDetail": "自动清理较早的记录", "settings.days": "{count} 天", "settings.forever": "永久保留", "settings.accessibility": "辅助功能", "settings.reduceMotion": "减少动态效果", "settings.reduceMotionDetail": "使用更安静的视觉效果", "settings.clear": "清除未置顶记录",
    "help.quickStart": "快速上手", "help.title": "复制过的内容，随手就能找到。", "help.intro": "掌握下面四个操作就可以开始使用 Mote。", "help.copyTitle": "照常复制", "help.copyBody": "文字、链接、图片、文件和富文本会一起保存。", "help.findTitle": "随时打开搜索", "help.findBody": "在任何应用中打开 Mote，输入关键词即可查找。", "help.pasteTitle": "快速粘贴", "help.pasteBody": "选择一条记录，直接粘贴回刚才使用的应用。", "help.multiTitle": "一次粘贴多条", "help.multiBody": "选择多条记录后，Mote 会从最早复制的一条开始依次粘贴。在窗口内可用 {shortcut} 切换多选模式。", "help.private": "默认保护隐私", "help.privateBody": "所有记录只保存在这台设备的本地数据库中。", "help.done": "知道了", "help.close": "关闭帮助",
    "error.close": "关闭错误提示", "error.actionNeeded": "需要处理", "error.pasteTitle": "Mote 无法自动粘贴", "error.genericTitle": "操作没有完成", "error.accessibilityDetail": "请在“系统设置 → 隐私与安全性 → 辅助功能”中允许 Mote，然后重试。", "error.openSettings": "打开系统设置", "error.dismiss": "关闭", "error.shortcutDifferent": "每个功能需要使用不同的快捷键。", "error.shortcutRegister": "这个快捷键已被其他应用占用，请换一个组合。", "error.shortcutInvalid": "Mote 无法识别这个快捷键，请重新设置。",
    "update.section": "软件更新", "update.settingsTitle": "Mote 更新", "update.version": "当前版本 {version}", "update.check": "立即检查", "update.checkingAction": "检查中…", "update.checkedAction": "已是最新", "update.checking": "正在连接 GitHub Releases…", "update.current": "已是最新版本", "update.checkFailed": "暂时无法连接 GitHub Releases", "update.eyebrow": "软件更新", "update.title": "Mote {version} 可以更新", "update.detail": "新版本将从 GitHub Releases 安全下载。", "update.install": "更新并重新启动", "update.later": "稍后", "update.downloading": "正在下载 {progress}%", "update.progress": "更新下载进度 {progress}%", "update.restarting": "更新已安装，Mote 正在重新启动…", "update.restartingShort": "正在重新启动…", "update.failedEyebrow": "更新已暂停", "update.failedTitle": "Mote 暂时无法更新", "update.failedDetail": "请检查网络后重试，剪贴板记录不会受到影响。", "update.retry": "重试",
    "detail.formats": "可用的剪贴板格式", "detail.compound": "联合复制 · {count} 项内容", "detail.item": "第 {count} 项", "type.text": "文字", "type.html": "HTML", "type.image": "图片", "type.files": "文件", "type.url": "链接", "type.color": "颜色", "type.code": "代码", "type.mixed": "联合复制", "detail.copied": "复制于{time}", "detail.todayAt": "今天 {time}", "detail.color": "剪贴板颜色", "detail.htmlSource": "HTML 源码", "unit.characters": "个字符", "unit.lines": "行", "key.enter": "回车", "key.space": "空格键",
  },
};

export function createI18n(preference = "auto") {
  const systemIsChinese = typeof navigator !== "undefined" && navigator.language.toLowerCase().startsWith("zh");
  const language = preference === "auto" ? systemIsChinese ? "zh" : "en" : preference === "zh-CN" ? "zh" : "en";
  const locale = language === "zh" ? "zh-CN" : "en-US";
  const t = (key, values = {}) => (messages[language][key] ?? messages.en[key] ?? key).replace(/\{(\w+)\}/g, (_, name) => values[name] ?? `{${name}}`);
  return { language, locale, t };
}

export function localizedItemDetail(item, t) {
  if (item.kind === "mixed") return `${t("type.mixed")} · ${new Set(item.representations?.map((representation) => representation.itemIndex)).size || 1}`;
  if (item.kind === "url") return t("type.url");
  if (item.kind === "color") return t("type.color");
  if (item.kind === "code") return `${t("type.code")} · ${item.content.split("\n").length} ${t("unit.lines")}`;
  if (item.kind === "html") return `HTML · ${item.content.split("\n").length} ${t("unit.lines")}`;
  if (item.kind === "text" || item.kind === "text-green") return `${t("type.text")} · ${[...item.content].length} ${t("unit.characters")}`;
  if (item.kind === "image") return item.detail.replace(/^Image/i, t("type.image"));
  return item.detail;
}
