const messages = {
  en: {
    "about.tagline": "Everything you copy, softly remembered.", "about.version": "Version {version}", "about.upToDate": "Up to date", "about.available": "Version {version} available", "about.checking": "Checking for updates…", "about.checkFailed": "Couldn’t check for updates", "about.downloading": "Downloading {progress}%", "about.restarting": "Restarting…", "about.check": "Check for Updates…", "about.checkingAction": "Checking…", "about.install": "Update and Restart", "about.retry": "Try Again", "about.copyright": "© 2026 Mote",
    "settings.categories": "Settings categories", "settings.category.general": "General", "settings.category.privacy": "Privacy", "settings.category.appearance": "Display", "settings.category.update": "Updates",
    "shortcut.eyebrow": "SHORTCUTS", "app.openShortcuts": "Open keyboard shortcuts", "help.ocrTitle": "Recognize text locally", "help.ocrBody": "Images keep the original picture. Search, copy, or paste recognized text only when you explicitly choose it.", "help.ocrDerived": "Derived locally · formulas stay raw", "help.nativePasteTitle": "Keep every real type", "help.nativePasteBody": "Text, images, files, and other native representations are written together in one clipboard change.",
    "help.guide": "Mote Tips", "help.guideSubtitle": "Learn every feature", "help.topicStart": "Getting started", "help.topicContent": "Rich content", "help.topicMultiple": "Multiple paste", "help.topicManage": "Organize & recover", "help.topicPermissions": "Permissions", "help.startTitle": "Copy, find, and paste.", "help.startIntro": "Mote stays out of the way until you need something you copied.", "help.exampleText": "A useful paragraph", "help.exampleSaved": "Saved automatically", "help.exampleSearch": "Search copied content…", "help.contentEyebrow": "SMART CONTENT", "help.contentTitle": "Mote understands what you copy.", "help.contentIntro": "A record keeps its real content and shows the actions that make sense for it.", "help.combinedTitle": "Keep a combined copy together", "help.combinedBody": "Text, images, and files copied at the same moment remain one ordered record.", "help.exampleCombined": "Image + caption", "help.exampleOneRecord": "One clipboard record", "help.colorsTitle": "Pick any color on screen", "help.colorsBody": "Press the color-picker shortcut, click once, and Mote copies and saves the HEX value.", "help.actionsTitle": "Use the right action", "help.actionsBody": "Open links in the browser, reveal files in their folder, and copy colors as HEX or RGB.", "help.multiIntro": "Collect several records, put them in the exact order you need, then paste them as one clipboard change.", "help.multiSelectTitle": "Build a combined paste", "help.queue1": "First answer", "help.queue2": "Second answer", "help.queue3": "Final link", "help.orderTitle": "Control the final order", "help.orderBody": "Move any numbered item earlier or later. Text, images, files, and other native content keep their real types.", "help.manageEyebrow": "KEEP CONTROL", "help.manageTitle": "Keep important things safe.", "help.manageIntro": "Pin records you reuse, recover accidental deletion, and see when a file has moved.", "help.pinTitle": "Pin what you reuse", "help.pinBody": "Pinned records stay at the top and are not removed when you clear history.", "help.undoTitle": "Undo a deletion", "help.undoBody": "After deleting one record or clearing history, use Undo within seven seconds to restore it.", "help.missingTitle": "Know when a file moved", "help.missingBody": "Mote marks file records whose original file is no longer at the saved location.", "help.permissionTitle": "See exactly what Mote needs.", "help.permissionIntro": "Permission status stays visible in Settings, with a direct path to fix anything missing.", "help.captureBody": "Clipboard recording saves new copies locally while it is enabled.",
    "shortcut.title": "Keyboard shortcuts", "shortcut.intro": "Customize global shortcuts and review every in-app command.", "shortcut.hint": "Global shortcuts can be changed. In-app commands reflect how Mote works today; Escape cancels recording.", "shortcut.close": "Close keyboard shortcuts", "shortcut.settingsDetail": "Open a separate panel to view and customize shortcuts",
    "shortcut.categories": "Shortcut categories", "shortcut.category.global": "Global actions", "shortcut.category.globalDetail": "Available while you are working in any app", "shortcut.category.browse": "Browse & reuse", "shortcut.category.browseDetail": "Navigate clipboard history without reaching for the pointer", "shortcut.category.multiple": "Multiple paste", "shortcut.category.multipleDetail": "Select, order, and paste several records as one change", "shortcut.search": "Focus search", "shortcut.searchDetail": "Start filtering clipboard history", "shortcut.navigate": "Move through records", "shortcut.navigateDetail": "Select the previous or next result", "shortcut.copy": "Copy selected record", "shortcut.copyDetail": "Restore it to the clipboard without hiding Mote", "shortcut.paste": "Use selected record", "shortcut.pasteDetail": "Paste or copy according to the Enter setting", "shortcut.dismiss": "Close or go back", "shortcut.dismissDetail": "Close dialogs, leave multiple paste, or hide Mote", "shortcut.select": "Select or remove record", "shortcut.selectDetail": "Toggle the focused item in the combined paste", "shortcut.selectAll": "Select all records", "shortcut.selectAllDetail": "Add every visible result", "shortcut.reorder": "Reorder selected record", "shortcut.reorderDetail": "Move the focused item earlier or later", "shortcut.pasteCombined": "Paste combined content", "shortcut.pasteCombinedDetail": "Write the ordered selection as one clipboard change",
    "help.previous": "Previous tip", "help.next": "Next tip", "help.pages": "Help pages", "help.screenshotTitle": "Capture a real scrolling window", "help.screenshotBody": "Choose the scrolling screenshot shortcut. Mote returns to the last app, scrolls its window, stitches the real frames locally, and stops at the bottom.", "help.exampleLocal": "History and derived data stay on this Mac",
    "action.openLink": "Open link", "action.showInFinder": "Show in folder", "action.copyHex": "Copy HEX", "action.copyRgb": "Copy RGB", "action.copyColor": "Copy {color}",
    "settings.permissions": "PERMISSIONS & STATUS", "permission.capture": "Clipboard recording", "permission.autoPaste": "Automatic paste", "permission.accessibilityCapture": "Control scrolling", "permission.screenCapture": "Screen Recording", "permission.screenCaptureNeeded": "Allow Mote under Privacy & Security → Screen & System Audio Recording", "permission.allow": "Allow", "permission.required": "Required", "permission.ready": "Ready", "permission.captureOff": "Turn on Capture clipboard above", "permission.accessibilityNeeded": "Allow Mote under Privacy & Security → Accessibility", "permission.fix": "Request Access", "permission.checkAgain": "Check again", "permission.checking": "Checking…", "permission.checkedReady": "Ready", "permission.stillNeeded": "Still needs access", "permission.restartHint": "If Mote is already enabled, quit and reopen it so macOS can apply the permission.", "permission.helpTitle": "Allow automatic paste", "permission.helpBody": "Mote needs Accessibility permission only to send the paste shortcut to the app you were using.", "permission.windowsPasteBody": "Mote sends Ctrl+V to the window you were using; no separate accessibility permission is required.",
    "undo.deletedOne": "Record deleted", "undo.deletedMany": "{count} records deleted", "undo.action": "Undo", "detail.fileMissing": "Original file is unavailable", "detail.extractedColors": "Colors from this image",
    "app.clipboard": "Clipboard", "app.pickColor": "Pick a color from the screen", "app.longScreenshot": "Capture a scrolling screenshot", "app.pinSelected": "Pin selected item", "app.openHelp": "Open help", "app.openSettings": "Open settings",
    "screenshot.title": "Scrolling screenshot", "screenshot.ready": "Window recognized", "screenshot.recognizedWindow": "Chrome window recognized", "screenshot.startAuto": "Start auto scroll", "screenshot.capturing": "Auto scrolling · {progress}%", "screenshot.paused": "Paused safely", "screenshot.reachedEnd": "Reached the end", "screenshot.stitched": "stitched", "screenshot.pause": "Pause", "screenshot.resume": "Resume", "screenshot.finish": "Finish & copy", "screenshot.saving": "Saving…", "screenshot.cancel": "Cancel screenshot", "screenshot.hint": "Move the wheel to pause · Space pauses or resumes · Esc cancels", "screenshot.nativeEyebrow": "REAL WINDOW CAPTURE", "screenshot.nativeTitle": "Capture a scrolling window", "screenshot.nativeIntro": "Mote returns to the app you were using, scrolls it, and stitches real frames locally.", "screenshot.targetWindow": "TARGET WINDOW", "screenshot.noTarget": "No recent window", "screenshot.findingTarget": "Finding the last app…", "screenshot.maxLength": "Maximum capture length", "screenshot.maxLengthDetail": "Mote still stops automatically at the bottom", "screenshot.lengthShort": "Short · 18 steps", "screenshot.lengthStandard": "Standard · 36 steps", "screenshot.lengthLong": "Long · 64 steps", "screenshot.nativeHint": "The target app comes forward while Mote captures. Hold Esc to stop early; the completed portion is kept.", "screenshot.startReal": "Start real capture", "screenshot.nativeCapturing": "Capturing…",
    "search.placeholder": "Search everything you copied…", "search.label": "Search clipboard history", "search.clear": "Clear search", "search.paste": "Paste", "search.open": "Open",
    "action.copy": "Copy", "action.copied": "Copied", "action.paste": "Paste", "action.pasted": "Pasted", "action.pastedCount": "Pasted {count}", "action.pastePlainText": "Paste as text", "action.copyPlainText": "Copy as text", "action.plainTextHint": "Use only the plain-text representation", "action.pin": "Pin", "action.pinned": "Pinned", "action.delete": "Delete", "action.cancel": "Cancel", "action.selectAll": "Select all",
    "empty.clipboard": "Your clipboard is clear", "confirm.clearTitle": "Clear clipboard history?", "confirm.clearDetail": "All unpinned records will be permanently removed. Pinned records will stay in Mote.", "confirm.clearAction": "Clear history", "confirm.clearing": "Clearing…", "confirm.cancel": "Cancel",
    "history.label": "Clipboard history", "history.loading": "Loading history…", "history.unavailable": "History unavailable", "history.selectedCount": "{count} selected", "history.select": "Select", "history.today": "Today", "history.earlier": "Earlier", "history.yesterday": "Yesterday", "history.noMatches": "No matches", "history.tryDifferent": "Try a different word or phrase.",
    "multi.label": "COMBINED PASTE", "multi.emptyTitle": "Select a few items", "multi.countTitle": "{count} item in the paste", "multi.countTitlePlural": "{count} items in the paste", "multi.explainer": "This entire pane previews one combined clipboard change. Reorder any item before pasting.", "multi.move": "Move", "multi.reorder": "Reorder", "multi.moveUp": "Move earlier", "multi.moveDown": "Move later", "multi.addRemove": "Select / remove", "multi.paste": "Paste combined content", "multi.pasteCount": "Paste {count} items together",
    "settings.title": "Settings", "settings.subtitle": "Mote preferences", "settings.general": "GENERAL", "settings.language": "Language", "settings.languageDetail": "Choose the language used in Mote", "settings.auto": "Follow system", "settings.english": "English", "settings.chinese": "简体中文", "settings.capture": "Capture clipboard", "settings.captureDetail": "Save new copies automatically", "settings.directPaste": "Paste on Enter", "settings.directPasteDetail": "Paste directly into the last app", "settings.launch": "Launch at login", "settings.launchDetail": "Keep Mote ready in the menu bar", "settings.shortcuts": "KEYBOARD SHORTCUTS", "settings.openMote": "Open Mote", "settings.openMoteDetail": "Available from any app", "settings.openMultiple": "Open multiple paste", "settings.openMultipleDetail": "Open directly in multiple selection", "settings.pickColor": "Pick screen color", "settings.pickColorDetail": "Click anywhere to copy and save a color", "settings.longScreenshot": "Scrolling screenshot", "settings.longScreenshotDetail": "Recognize a window, auto-scroll, and stitch", "settings.toggleMultiple": "Toggle multiple selection", "settings.toggleMultipleDetail": "Works while Mote is open", "settings.pressKeys": "Press keys…", "settings.privacy": "PRIVACY & STORAGE", "settings.ignorePasswords": "Ignore password managers", "settings.ignorePasswordsDetail": "Skip copies from sensitive apps", "settings.historyLimit": "History limit", "settings.historyLimitDetail": "Maximum saved items", "settings.keepHistory": "Keep history", "settings.keepHistoryDetail": "Automatically remove old items", "settings.days": "{count} days", "settings.forever": "Forever", "settings.accessibility": "ACCESSIBILITY", "settings.reduceMotion": "Reduce motion", "settings.reduceMotionDetail": "Use quieter visual effects", "settings.clear": "Clear unpinned history",
    "help.quickStart": "QUICK START", "help.title": "Your clipboard, close at hand.", "help.intro": "Four simple actions are all you need to use Mote.", "help.copyTitle": "Copy anything", "help.copyBody": "Text, links, images, files, and rich content are saved together.", "help.findTitle": "Find it instantly", "help.findBody": "Open Mote from anywhere, then type to search your history.", "help.pasteTitle": "Paste it back", "help.pasteBody": "Choose an item and send it straight to the app you were using.", "help.multiTitle": "Paste several items", "help.multiBody": "Select several records, reorder the numbered list, and paste it exactly as shown. Toggle inside Mote with {shortcut}.", "help.private": "Private by default", "help.privateBody": "Everything stays in a local SQLite database on this device.", "help.done": "Got it", "help.close": "Close help",
    "error.close": "Close error", "error.actionNeeded": "ACTION NEEDED", "error.pasteTitle": "Mote couldn’t paste automatically", "error.genericTitle": "Something went wrong", "error.accessibilityDetail": "Allow Mote under System Settings → Privacy & Security → Accessibility, then try again.", "error.openSettings": "Open System Settings", "error.dismiss": "Close", "error.shortcutDifferent": "Choose a different key combination for each shortcut.", "error.shortcutRegister": "That shortcut is already in use. Try another key combination.", "error.shortcutInvalid": "Mote couldn’t understand that shortcut. Please record it again.",
    "update.section": "SOFTWARE UPDATE", "update.settingsTitle": "Mote updates", "update.version": "Version {version}", "update.check": "Check now", "update.checkingAction": "Checking…", "update.checkedAction": "Up to date", "update.checking": "Contacting GitHub Releases…", "update.current": "Mote is up to date", "update.checkFailed": "Couldn’t reach GitHub Releases", "update.eyebrow": "SOFTWARE UPDATE", "update.title": "Mote {version} is available", "update.detail": "This update is ready to download from GitHub Releases.", "update.install": "Update and restart", "update.later": "Later", "update.downloading": "Downloading {progress}%", "update.progress": "Update download {progress}%", "update.restarting": "The update is installed. Mote is restarting…", "update.restartingShort": "Restarting…", "update.failedEyebrow": "UPDATE PAUSED", "update.failedTitle": "Mote couldn’t update", "update.failedDetail": "Check your connection and try again. Your clipboard history is unchanged.", "update.retry": "Try again",
    "detail.formats": "Available clipboard formats", "detail.compound": "Combined copy · {count} items", "detail.item": "Item {count}", "detail.sourceApp": "From {app}", "type.text": "Text", "type.html": "HTML", "type.image": "Image", "type.files": "Files", "type.url": "Link", "type.color": "Color", "type.code": "Code", "type.mixed": "Combined copy", "detail.copied": "Copied {time}", "detail.todayAt": "today at {time}", "detail.color": "Clipboard color", "detail.htmlSource": "HTML source", "ocr.title": "Recognized text", "ocr.derived": "Derived from image", "ocr.pending": "Waiting for local text recognition…", "ocr.processing": "Recognizing text on this device…", "ocr.empty": "No readable text found in this image", "ocr.copyText": "Copy recognized text", "ocr.pasteText": "Paste recognized text", "ocr.formulaWarning": "Formula characters may be recognized, but mathematical layout and structure may not be preserved.", "unit.characters": "characters", "unit.lines": "lines", "key.enter": "Enter", "key.space": "Space",
  },
  zh: {
    "about.tagline": "复制过的内容，都会被轻轻记住。", "about.version": "版本 {version}", "about.upToDate": "已是最新版本", "about.available": "发现版本 {version}", "about.checking": "正在检查更新…", "about.checkFailed": "暂时无法检查更新", "about.downloading": "正在下载 {progress}%", "about.restarting": "正在重新启动…", "about.check": "检查更新…", "about.checkingAction": "检查中…", "about.install": "更新并重新启动", "about.retry": "重试", "about.copyright": "© 2026 Mote",
    "settings.categories": "设置分类", "settings.category.general": "常规", "settings.category.privacy": "隐私", "settings.category.appearance": "显示", "settings.category.update": "更新",
    "shortcut.eyebrow": "快捷键", "app.openShortcuts": "打开键盘快捷键", "help.ocrTitle": "在本机识别图片文字", "help.ocrBody": "图片会始终保留原图；只有明确选择时，才复制或粘贴识别出来的文字。", "help.ocrDerived": "本机衍生 · 公式保留为原文", "help.nativePasteTitle": "保留每一种真实类型", "help.nativePasteBody": "文字、图片、文件和其他原生内容会一起写入同一次剪贴板变化。",
    "help.guide": "Mote 技巧", "help.guideSubtitle": "了解每一项功能", "help.topicStart": "开始使用", "help.topicContent": "丰富内容", "help.topicMultiple": "多条粘贴", "help.topicManage": "整理与恢复", "help.topicPermissions": "权限说明", "help.startTitle": "复制、查找，然后粘贴。", "help.startIntro": "Mote 平时安静地记录，需要时再帮你找回复制过的内容。", "help.exampleText": "一段有用的文字", "help.exampleSaved": "已经自动保存", "help.exampleSearch": "搜索复制过的内容…", "help.contentEyebrow": "智能内容", "help.contentTitle": "复制什么，就按什么来处理。", "help.contentIntro": "每条记录保留真实内容，并只显示适合这类内容的操作。", "help.combinedTitle": "联合复制保持在一起", "help.combinedBody": "同一次复制中的文字、图片和文件会按原顺序保存在一条记录中。", "help.exampleCombined": "图片 + 说明文字", "help.exampleOneRecord": "同一条剪贴板记录", "help.colorsTitle": "提取屏幕上的任意颜色", "help.colorsBody": "按下取色快捷键，点击一次，Mote 就会复制 HEX 色值并保存为颜色记录。", "help.actionsTitle": "显示合适的操作", "help.actionsBody": "链接可以打开，文件可以在访达中显示，颜色可以复制为 HEX 或 RGB。", "help.multiIntro": "先收集多条记录，调整顺序，再把它们作为一次联合剪贴板写入。", "help.multiSelectTitle": "建立合并粘贴", "help.queue1": "第一段回答", "help.queue2": "第二段回答", "help.queue3": "最后一个链接", "help.orderTitle": "控制最终粘贴顺序", "help.orderBody": "每条记录都可以前移或后移；文字、图片、文件及其他原生内容都会保留真实类型。", "help.manageEyebrow": "安心整理", "help.manageTitle": "重要内容不会轻易丢失。", "help.manageIntro": "常用内容可以置顶，误删可以撤销，原文件移动后也会明确提示。", "help.pinTitle": "置顶常用内容", "help.pinBody": "置顶记录会留在列表顶部，清除历史时也不会被删除。", "help.undoTitle": "撤销误删", "help.undoBody": "删除单条记录或清空历史后，可在 7 秒内点击“撤销”恢复。", "help.missingTitle": "发现文件已经移动", "help.missingBody": "如果原文件不在保存时的位置，Mote 会在记录和预览中标记失效。", "help.permissionTitle": "清楚知道 Mote 需要什么。", "help.permissionIntro": "设置中会显示权限状态，缺少权限时可以直接前往修复。", "help.captureBody": "开启后，Mote 会在本机自动保存新的复制内容。",
    "shortcut.title": "键盘快捷键", "shortcut.intro": "自定义全局快捷键，并查看 Mote 内的全部键盘操作。", "shortcut.hint": "全局快捷键可以修改；应用内操作与当前真实功能保持一致。录制时按 Esc 取消。", "shortcut.close": "关闭快捷键设置", "shortcut.settingsDetail": "在单独的面板中查看并自定义快捷键",
    "shortcut.categories": "快捷键分类", "shortcut.category.global": "全局操作", "shortcut.category.globalDetail": "在其他应用中工作时也能随时使用", "shortcut.category.browse": "浏览与取用", "shortcut.category.browseDetail": "不离开键盘即可查找并使用剪贴板记录", "shortcut.category.multiple": "多条粘贴", "shortcut.category.multipleDetail": "选择、排序，再作为一次联合剪贴板写入", "shortcut.search": "聚焦搜索", "shortcut.searchDetail": "立即筛选剪贴板记录", "shortcut.navigate": "切换记录", "shortcut.navigateDetail": "选择上一条或下一条结果", "shortcut.copy": "复制当前记录", "shortcut.copyDetail": "恢复到剪贴板，但不隐藏 Mote", "shortcut.paste": "使用当前记录", "shortcut.pasteDetail": "根据回车设置执行粘贴或复制", "shortcut.dismiss": "关闭或返回", "shortcut.dismissDetail": "关闭弹窗、退出多选或隐藏 Mote", "shortcut.select": "选择或移除记录", "shortcut.selectDetail": "切换当前记录是否加入联合粘贴", "shortcut.selectAll": "选择全部记录", "shortcut.selectAllDetail": "加入当前显示的全部结果", "shortcut.reorder": "调整当前记录顺序", "shortcut.reorderDetail": "将当前记录向前或向后移动", "shortcut.pasteCombined": "粘贴联合内容", "shortcut.pasteCombinedDetail": "按当前顺序写入一次联合剪贴板",
    "help.previous": "上一项技巧", "help.next": "下一项技巧", "help.pages": "帮助页面", "help.screenshotTitle": "截取真实滚动窗口", "help.screenshotBody": "使用滚动长截图快捷键后，Mote 会回到刚才的应用，自动滚动真实窗口，在本机逐帧拼接，并在到达底部时停止。", "help.exampleLocal": "历史记录和衍生数据只保存在这台 Mac",
    "action.openLink": "打开链接", "action.showInFinder": "在文件夹中显示", "action.copyHex": "复制 HEX", "action.copyRgb": "复制 RGB", "action.copyColor": "复制 {color}",
    "settings.permissions": "权限与状态", "permission.capture": "剪贴板记录", "permission.autoPaste": "自动粘贴", "permission.accessibilityCapture": "控制自动滚动", "permission.screenCapture": "屏幕录制", "permission.screenCaptureNeeded": "请在“隐私与安全性 → 屏幕与系统音频录制”中允许 Mote", "permission.allow": "允许", "permission.required": "需要授权", "permission.ready": "可以使用", "permission.captureOff": "请先打开上方的“记录剪贴板”", "permission.accessibilityNeeded": "请在“隐私与安全性 → 辅助功能”中允许 Mote", "permission.fix": "请求授权", "permission.checkAgain": "重新检查", "permission.checking": "检查中…", "permission.checkedReady": "可以使用", "permission.stillNeeded": "仍需授权", "permission.restartHint": "如果 Mote 已经开启，请退出并重新打开它，让 macOS 应用权限。", "permission.helpTitle": "允许自动粘贴", "permission.helpBody": "Mote 只会使用辅助功能权限，把粘贴快捷键发送到你刚才使用的应用。", "permission.windowsPasteBody": "Mote 会把 Ctrl+V 发送到你刚才使用的窗口，不需要单独授予辅助功能权限。",
    "undo.deletedOne": "已删除 1 条记录", "undo.deletedMany": "已删除 {count} 条记录", "undo.action": "撤销", "detail.fileMissing": "原文件已失效", "detail.extractedColors": "从图片中提取的颜色",
    "app.clipboard": "剪贴板", "app.pickColor": "从屏幕提取颜色", "app.longScreenshot": "截取自动滚动长截图", "app.pinSelected": "置顶当前记录", "app.openHelp": "打开帮助", "app.openSettings": "打开设置",
    "screenshot.title": "滚动长截图", "screenshot.ready": "已识别窗口", "screenshot.recognizedWindow": "已识别 Chrome 窗口", "screenshot.startAuto": "开始自动滚动", "screenshot.capturing": "正在自动滚动 · {progress}%", "screenshot.paused": "已安全暂停", "screenshot.reachedEnd": "已经到达底部", "screenshot.stitched": "已拼接", "screenshot.pause": "暂停", "screenshot.resume": "继续", "screenshot.finish": "完成并复制", "screenshot.saving": "正在保存…", "screenshot.cancel": "取消截图", "screenshot.hint": "滚动滚轮即可暂停 · 空格暂停或继续 · Esc 取消", "screenshot.nativeEyebrow": "真实窗口捕获", "screenshot.nativeTitle": "截取真实滚动窗口", "screenshot.nativeIntro": "Mote 会回到你刚才使用的应用，自动滚动，并在本机拼接真实画面。", "screenshot.targetWindow": "目标窗口", "screenshot.noTarget": "没有最近使用的窗口", "screenshot.findingTarget": "正在查找刚才的应用…", "screenshot.maxLength": "最长捕获范围", "screenshot.maxLengthDetail": "到达底部时仍会自动停止", "screenshot.lengthShort": "较短 · 18 次滚动", "screenshot.lengthStandard": "标准 · 36 次滚动", "screenshot.lengthLong": "较长 · 64 次滚动", "screenshot.nativeHint": "捕获时目标应用会回到前台。按住 Esc 可以提前结束，已经拼接的部分仍会保留。", "screenshot.startReal": "开始真实捕获", "screenshot.nativeCapturing": "正在捕获…",
    "search.placeholder": "搜索复制过的内容…", "search.label": "搜索剪贴板记录", "search.clear": "清除搜索", "search.paste": "粘贴", "search.open": "打开",
    "action.copy": "复制", "action.copied": "已复制", "action.paste": "粘贴", "action.pasted": "已粘贴", "action.pastedCount": "已粘贴 {count} 条", "action.pastePlainText": "粘贴为纯文本", "action.copyPlainText": "复制为纯文本", "action.plainTextHint": "只使用这条记录的纯文本内容", "action.pin": "置顶", "action.pinned": "已置顶", "action.delete": "删除", "action.cancel": "取消", "action.selectAll": "全部选择",
    "empty.clipboard": "剪贴板记录为空", "confirm.clearTitle": "清除剪贴板记录？", "confirm.clearDetail": "所有未置顶的记录都会被永久删除，已经置顶的记录会继续保留。", "confirm.clearAction": "清除记录", "confirm.clearing": "正在清除…", "confirm.cancel": "取消",
    "history.label": "剪贴板记录", "history.loading": "正在加载记录…", "history.unavailable": "暂时无法读取记录", "history.selectedCount": "已选择 {count} 条", "history.select": "多选", "history.today": "今天", "history.earlier": "更早", "history.yesterday": "昨天", "history.noMatches": "没有找到结果", "history.tryDifferent": "换个关键词试试。",
    "multi.label": "合并粘贴", "multi.emptyTitle": "请选择几条记录", "multi.countTitle": "本次粘贴包含 {count} 项", "multi.countTitlePlural": "本次粘贴包含 {count} 项", "multi.explainer": "右侧整个区域就是一次联合剪贴板写入的预览；粘贴前可调整任意内容的顺序。", "multi.move": "移动", "multi.reorder": "调整顺序", "multi.moveUp": "向前移动", "multi.moveDown": "向后移动", "multi.addRemove": "选择 / 取消", "multi.paste": "粘贴合并内容", "multi.pasteCount": "合并粘贴 {count} 项",
    "settings.title": "设置", "settings.subtitle": "Mote 偏好设置", "settings.general": "常规", "settings.language": "语言", "settings.languageDetail": "选择 Mote 使用的界面语言", "settings.auto": "跟随系统", "settings.english": "English", "settings.chinese": "简体中文", "settings.capture": "记录剪贴板", "settings.captureDetail": "自动保存新复制的内容", "settings.directPaste": "回车直接粘贴", "settings.directPasteDetail": "直接粘贴到刚才使用的应用", "settings.launch": "登录时启动", "settings.launchDetail": "让 Mote 随时在菜单栏待命", "settings.shortcuts": "快捷键", "settings.openMote": "打开 Mote", "settings.openMoteDetail": "可在任何应用中使用", "settings.openMultiple": "打开多条粘贴", "settings.openMultipleDetail": "直接进入多选模式", "settings.pickColor": "屏幕取色", "settings.pickColorDetail": "点击任意位置，复制并保存颜色", "settings.longScreenshot": "滚动长截图", "settings.longScreenshotDetail": "识别窗口、自动滚动并智能拼接", "settings.toggleMultiple": "切换多选模式", "settings.toggleMultipleDetail": "在 Mote 窗口内使用", "settings.pressKeys": "请按快捷键…", "settings.privacy": "隐私与存储", "settings.ignorePasswords": "忽略密码管理器", "settings.ignorePasswordsDetail": "不记录敏感应用中的复制内容", "settings.historyLimit": "记录上限", "settings.historyLimitDetail": "最多保存多少条记录", "settings.keepHistory": "保留时间", "settings.keepHistoryDetail": "自动清理较早的记录", "settings.days": "{count} 天", "settings.forever": "永久保留", "settings.accessibility": "辅助功能", "settings.reduceMotion": "减少动态效果", "settings.reduceMotionDetail": "使用更安静的视觉效果", "settings.clear": "清除未置顶记录",
    "help.quickStart": "快速上手", "help.title": "复制过的内容，随手就能找到。", "help.intro": "掌握下面四个操作就可以开始使用 Mote。", "help.copyTitle": "照常复制", "help.copyBody": "文字、链接、图片、文件和富文本会一起保存。", "help.findTitle": "随时打开搜索", "help.findBody": "在任何应用中打开 Mote，输入关键词即可查找。", "help.pasteTitle": "快速粘贴", "help.pasteBody": "选择一条记录，直接粘贴回刚才使用的应用。", "help.multiTitle": "一次粘贴多条", "help.multiBody": "选择多条记录后，按编号调整顺序，再按照预览内容粘贴。在窗口内可用 {shortcut} 切换多选模式。", "help.private": "默认保护隐私", "help.privateBody": "所有记录只保存在这台设备的本地数据库中。", "help.done": "知道了", "help.close": "关闭帮助",
    "error.close": "关闭错误提示", "error.actionNeeded": "需要处理", "error.pasteTitle": "Mote 无法自动粘贴", "error.genericTitle": "操作没有完成", "error.accessibilityDetail": "请在“系统设置 → 隐私与安全性 → 辅助功能”中允许 Mote，然后重试。", "error.openSettings": "打开系统设置", "error.dismiss": "关闭", "error.shortcutDifferent": "每个功能需要使用不同的快捷键。", "error.shortcutRegister": "这个快捷键已被其他应用占用，请换一个组合。", "error.shortcutInvalid": "Mote 无法识别这个快捷键，请重新设置。",
    "update.section": "软件更新", "update.settingsTitle": "Mote 更新", "update.version": "当前版本 {version}", "update.check": "立即检查", "update.checkingAction": "检查中…", "update.checkedAction": "已是最新", "update.checking": "正在连接 GitHub Releases…", "update.current": "已是最新版本", "update.checkFailed": "暂时无法连接 GitHub Releases", "update.eyebrow": "软件更新", "update.title": "Mote {version} 可以更新", "update.detail": "新版本将从 GitHub Releases 安全下载。", "update.install": "更新并重新启动", "update.later": "稍后", "update.downloading": "正在下载 {progress}%", "update.progress": "更新下载进度 {progress}%", "update.restarting": "更新已安装，Mote 正在重新启动…", "update.restartingShort": "正在重新启动…", "update.failedEyebrow": "更新已暂停", "update.failedTitle": "Mote 暂时无法更新", "update.failedDetail": "请检查网络后重试，剪贴板记录不会受到影响。", "update.retry": "重试",
    "detail.formats": "可用的剪贴板格式", "detail.compound": "联合复制 · {count} 项内容", "detail.item": "第 {count} 项", "detail.sourceApp": "来源：{app}", "type.text": "文字", "type.html": "HTML", "type.image": "图片", "type.files": "文件", "type.url": "链接", "type.color": "颜色", "type.code": "代码", "type.mixed": "联合复制", "detail.copied": "复制于{time}", "detail.todayAt": "今天 {time}", "detail.color": "剪贴板颜色", "detail.htmlSource": "HTML 源码", "ocr.title": "识别文字", "ocr.derived": "从图片衍生", "ocr.pending": "等待本地文字识别…", "ocr.processing": "正在本机识别文字…", "ocr.empty": "这张图片中没有发现可读文字", "ocr.copyText": "复制识别文字", "ocr.pasteText": "粘贴识别文字", "ocr.formulaWarning": "公式字符可能被识别，但数学排版和结构不一定能完整保留。", "unit.characters": "个字符", "unit.lines": "行", "key.enter": "回车", "key.space": "空格键",
  },
};

export function createI18n(preference = "auto") {
  const systemIsChinese = typeof navigator !== "undefined" && navigator.language.toLowerCase().startsWith("zh");
  const language = preference === "auto" ? systemIsChinese ? "zh" : "en" : preference === "zh-CN" ? "zh" : "en";
  const locale = language === "zh" ? "zh-CN" : "en-US";
  const t = (key, values = {}) => (messages[language][key] ?? messages.en[key] ?? key).replace(/\{(\w+)\}/g, (_, name) => values[name] ?? `{${name}}`);
  return { language, locale, t };
}

export function localizedItemDetail(item, t) {
  if (item.kind === "mixed") return `${t("type.mixed")} · ${new Set(item.representations?.map((representation) => representation.itemIndex)).size || 1}`;
  if (item.kind === "url") return t("type.url");
  if (item.kind === "color") return t("type.color");
  if (item.kind === "code") return `${t("type.code")} · ${item.content.split("\n").length} ${t("unit.lines")}`;
  if (item.kind === "html") return `HTML · ${item.content.split("\n").length} ${t("unit.lines")}`;
  if (item.kind === "text" || item.kind === "text-green") return `${t("type.text")} · ${[...item.content].length} ${t("unit.characters")}`;
  if (item.kind === "image") return item.detail.replace(/^Image/i, t("type.image"));
  return item.detail;
}
